name: Go

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  buildLinux:
    name: Build Linux
    runs-on: ubuntu-latest
    steps:

    - name: Set up Go 1.x
      uses: actions/setup-go@v2
      with:
        go-version: ^1.15
      id: go

    - name: Check out code into the Go module directory
      uses: actions/checkout@v2

    - name: Get dependencies
      run: |
        go mod tidy

    - name: Test
      run: go test -v ./...

    - name: Build Linux amd64
      run: GOOS=linux GOARCH=amd64 go build -ldflags="-s -w" -o jwt github.com/c16a/jwt
    
    - name: Build Linux arm64
      run: GOOS=linux GOARCH=arm64 go build -ldflags="-s -w" -o jwt github.com/c16a/jwt

  buildWindows:
    name: Build Windows
    runs-on: windows-latest
    steps:

      - name: Set up Go 1.x
        uses: actions/setup-go@v2
        with:
          go-version: ^1.15
        id: go

      - name: Check out code into the Go module directory
        uses: actions/checkout@v2

      - name: Get dependencies
        run: |
          go mod tidy

      - name: Test
        run: go test -v ./...

      - name: Build Windows amd64
        run: GOOS=windows GOARCH=amd64 go build -ldflags="-s -w" -o jwt github.com/c16a/jwt

  buildMac:
    name: Build Mac
    runs-on: macos-latest
    steps:

      - name: Set up Go 1.x
        uses: actions/setup-go@v2
        with:
          go-version: ^1.15
        id: go

      - name: Check out code into the Go module directory
        uses: actions/checkout@v2

      - name: Get dependencies
        run: |
          go mod tidy

      - name: Test
        run: go test -v ./...

      - name: Build Mac amd64
        run: GOOS=darwin GOARCH=amd64 go build -ldflags="-s -w" -o jwt github.com/c16a/jwt

      - name: Build Mac arm64
        run: GOOS=darwin GOARCH=arm64 go build -ldflags="-s -w" -o jwt github.com/c16a/jwt


